// Code Generated by Sidekick is for learning and experimentation purposes only.
export type UtcIsoString = string; // e.g., "2026-02-05T18:22:11.123Z"

export function utcNowIso(): UtcIsoString {
    return new Date().toISOString(); // always UTC, always ends with "Z"
}

export function parseUtcIso(utcIso: UtcIsoString): Date {
    // JS Date stores an absolute instant; "Z" means UTC.
    const d = new Date(utcIso);
    if (Number.isNaN(d.getTime())) throw new Error(`Invalid UTC ISO timestamp: ${utcIso}`);
    return d;
}

// Example: attach timestamp when sending a chat message
export function makeOutgoingChat(text: string) {
    return {
        type: "chat",
        text,
        clientSentAtUtc: utcNowIso(),
    };
}