# Model Provider Constants
class ModelProviderName:
    OPENAI = "openai"
    ANTHROPIC = "anthropic"
    GOOGLE = "google"
    OLLAMA = "ollama"
    AZURE = "azure"
    AWS = "aws"
    TOGETHER = "together"
    MISTRAL = "mistral"
    META = "meta"
    XAI = "xai"
    DATABRICKS = "databricks"
    COHERE = "cohere"
    MICROSOFT = "microsoft"
    TII = "tii"
    ALIBABA = "alibaba"
    DEEPSEEK = "deepseek"
    HUGGINGFACE = "huggingface"
